// <auto-generated />
namespace NCDSB_ConferenceForm_Submit.DAL.ConferenceFormMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AutocompleteWorkAround : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AutocompleteWorkAround));
        
        string IMigrationMetadata.Id
        {
            get { return "201804111627393_AutocompleteWorkAround"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
